[project]
name = "project-videoproduction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "black>=25.9.0",
    "flask>=3.1.2",
    "isort>=6.1.0",
    "pylint>=3.3.8",
]
