# Generated by Django 5.2.7 on 2025-10-12 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_video_preview_alter_video_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='preview',
        ),
    ]
