# Generated by Django 5.2.7 on 2025-10-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_remove_video_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
