# Generated by Django 5.2.7 on 2025-10-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0009_video_preview_url_alter_video_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="video_id",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="preview_url",
            field=models.URLField(blank=True, editable=False, null=True),
        ),
    ]
