export const exampleCategories = [
    { id: 2, name: 'Von allem etwas' },
    { id: 3, name: 'Spiritualität & Mindset' },
    { id: 4, name: 'Investment & Kapital' },
    { id: 5, name: 'Kommunen & Städte' },
    { id: 6, name: 'Solar & Energie' },
    { id: 7, name: 'Camping' },
    { id: 8, name: 'Immobilien' },
    { id: 9, name: 'Industrie' },
    { id: 10, name: 'Dienstleister' },
    { id: 11, name: 'Gartenlandschaftsbau' },
    { id: 12, name: 'Museum' },
    { id: 13, name: 'Handwerk' },
    { id: 14, name: 'Finanzdienstleistung' },
    { id: 15, name: 'Architektur' },
    { id: 16, name: 'Automobil' },
    { id: 17, name: 'Pflege' },
    { id: 18, name: 'Filmemacher' },
  ];