# Generated by Django 5.2.7 on 2025-11-11 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_alter_faq_options_faq_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['order'], 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
    ]
